title: Be Framework Blog
description: Ontological programming for the AI era
url: https://be-framework.github.io
baseurl: /be-blog
markdown: kramdown
plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
